#!/usr/bin/env python3
"""Generate TOOLS.md and the README tool summary from the [ToolProvider] sources.

Usage:
    python scripts/generate_tools_doc.py            # write TOOLS.md + README summary
    python scripts/generate_tools_doc.py --check    # exit 1 if either file is stale
"""

import itertools
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EDITOR = ROOT / "Editor"
TOOLS_MD = ROOT / "TOOLS.md"
README = ROOT / "README.md"
README_CN = ROOT / "README_CN.md"
POLICY = EDITOR / "MCP" / "Server" / "MCPToolExportPolicy.cs"

SUMMARY_START = "<!-- tools-summary:start -->"
SUMMARY_END = "<!-- tools-summary:end -->"

PROVIDER_RE = re.compile(r'\[ToolProvider\("([^"]+)"\)\][\s\S]{0,200}?class\s+(\w+)')
METHOD_RE = re.compile(r'^ {8}public static (?:async )?[\w\.\<\>\[\]\,\s\?]+? (\w+)\s*\(', re.M)
STRING_RE = re.compile(r'"((?:[^"\\]|\\.)*)"')


def snake_case(pascal):
    out = []
    for i, c in enumerate(pascal):
        if c.isupper() and i > 0 and (pascal[i - 1].islower() or (i + 1 < len(pascal) and pascal[i + 1].islower())):
            out.append("_")
        out.append(c.lower())
    return "".join(out)


def attribute_block(text, method_start):
    """The attribute lines directly above a method declaration, in source order."""
    lines = reversed(text[:method_start].splitlines())
    above = itertools.takewhile(lambda l: l.strip() and l.strip() not in ("{", "}"), lines)
    return "\n".join(reversed(list(above)))


def description_of(block):
    m = re.search(r'\[Description\(([\s\S]*?)\)\]', block)
    if not m:
        return ""
    joined = "".join(STRING_RE.findall(m.group(1)))
    joined = joined.replace('\\"', '"').replace("\\n", " ").replace("|", "\\|")
    joined = re.sub(r"\s+", " ", joined).strip()
    return re.split(r"(?<=\.)\s", joined, maxsplit=1)[0]


def core_tools():
    text = POLICY.read_text(encoding="utf-8")
    m = re.search(r'CoreTools = new HashSet<string>\(StringComparer\.OrdinalIgnoreCase\)\s*\{([\s\S]*?)\};', text)
    return set(STRING_RE.findall(m.group(1))) if m else set()


def collect():
    """{module: {tool_name: description}}, biggest module first."""
    texts = [f.read_text(encoding="utf-8", errors="ignore")
             for f in EDITOR.rglob("*.cs") if "Tests" not in f.parts]

    class_to_module = {}
    for text in texts:
        for m in PROVIDER_RE.finditer(text):
            class_to_module[m.group(2)] = m.group(1)

    modules = {}
    for text in texts:
        declared = [c for c in class_to_module if re.search(r"class\s+%s\b" % c, text)]
        if not declared:
            continue
        module = class_to_module[declared[0]]
        for m in METHOD_RE.finditer(text):
            name = snake_case(m.group(1))
            modules.setdefault(module, {})[name] = description_of(attribute_block(text, m.start()))
    return dict(sorted(modules.items(), key=lambda kv: (-len(kv[1]), kv[0])))


def render_tools_md(modules, core, total):
    out = [
        "# KitWright MCP for Unity — Tool Reference",
        "",
        "> Auto-generated by `scripts/generate_tools_doc.py` from the `[ToolProvider]` sources.",
        "> Do not hand-edit — run the script after adding, renaming, or removing a tool.",
        "",
        f"**{total} tools across {len(modules)} modules.** Tools marked *(core)* are exposed by the "
        "default `core` profile; the rest need `full` (or `set_tool_profile`).",
        "",
    ]
    for module, tools in modules.items():
        out += [f"## {module} ({len(tools)})", "", "| Tool | Description |", "|------|-------------|"]
        for name in sorted(tools):
            label = f"`{name}` *(core)*" if name in core else f"`{name}`"
            out.append(f"| {label} | {tools[name] or '—'} |")
        out.append("")
    return "\n".join(out)


SUMMARY_TEXT = {
    "en": {
        "header": "| Module | Tools | Module | Tools |\n|--------|-------|--------|-------|",
        "intro": "KitWright MCP for Unity ships **{total} tool functions across {modules} modules** "
                 "(`core` profile exposes {core} of them).",
        "link": "> 📖 Every tool with its description: [TOOLS.md](TOOLS.md).",
    },
    "cn": {
        "header": "| 模块 | 工具数 | 模块 | 工具数 |\n|------|--------|------|--------|",
        "intro": "KitWright MCP for Unity 当前提供 **{total} 个工具函数，覆盖 {modules} 个模块**"
                 "（`core` profile 暴露其中 {core} 个）。",
        "link": "> 📖 每个工具及其说明见 [TOOLS.md](TOOLS.md)。",
    },
}


def render_summary(modules, core, total, lang):
    text = SUMMARY_TEXT[lang]
    rows = [text["header"]]
    ordered = list(modules)
    half = (len(ordered) + 1) // 2
    for a, b in itertools.zip_longest(ordered[:half], ordered[half:]):
        cell_b = f"**{b}** | {len(modules[b])}" if b else " | "
        rows.append(f"| **{a}** | {len(modules[a])} | {cell_b} |")
    return "\n".join([
        SUMMARY_START,
        text["intro"].format(total=total, modules=len(modules), core=len(core)),
        "",
        *rows,
        "",
        text["link"],
        SUMMARY_END,
    ])


def splice_readme(path, summary):
    text = path.read_text(encoding="utf-8")
    start, end = text.find(SUMMARY_START), text.find(SUMMARY_END)
    if start == -1 or end == -1:
        sys.exit(f"{path.name} is missing the {SUMMARY_START} / {SUMMARY_END} markers.")
    return text[:start] + summary + text[end + len(SUMMARY_END):]


def main():
    modules = collect()
    core = core_tools()
    total = sum(len(t) for t in modules.values())
    generated = {
        TOOLS_MD: render_tools_md(modules, core, total),
        README: splice_readme(README, render_summary(modules, core, total, "en")),
        README_CN: splice_readme(README_CN, render_summary(modules, core, total, "cn")),
    }

    stale = [p.name for p, content in generated.items()
             if not p.exists() or p.read_text(encoding="utf-8") != content]

    if "--check" in sys.argv:
        if stale:
            sys.exit("Stale, re-run scripts/generate_tools_doc.py: " + ", ".join(stale))
        print("Up to date.")
        return

    for path, content in generated.items():
        path.write_text(content, encoding="utf-8")
    print(f"Wrote TOOLS.md ({total} tools, {len(modules)} modules) + README / README_CN summaries.")


if __name__ == "__main__":
    main()
